apiVersion: v1
kind: Service
metadata:
  name: cronzimus-svc
spec:
  ports:
    - name: cronzimus-port
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  selector:
    app: cronzimus
